#!/bin/bash
# Script to download free sound effects and music for SimpleSurvivor
# All sounds are from OpenGameArt.org and Freesound.org (CC0/CC-BY licenses)

SOUNDS_DIR="assets/sounds"
MUSIC_DIR="assets/music"

echo "=== SimpleSurvivor Audio Downloader ==="
echo ""

# Create directories if they don't exist
mkdir -p "$SOUNDS_DIR"
mkdir -p "$MUSIC_DIR"

echo "Downloading sound effects..."

# Note: These are placeholder URLs. You should replace them with actual free sound URLs
# or use the manual download instructions below.

echo ""
echo "=== MANUAL DOWNLOAD INSTRUCTIONS ==="
echo ""
echo "Since direct downloads from sound libraries require authentication,"
echo "please download the following sounds manually:"
echo ""
echo "--- SOUND EFFECTS (save as .wav in assets/sounds/) ---"
echo ""
echo "1. shoot.wav - Laser/blaster sound"
echo "   https://opengameart.org/content/laser-fire"
echo "   https://freesound.org/search/?q=laser+shot"
echo ""
echo "2. explosion.wav - Explosion sound"
echo "   https://opengameart.org/content/explosion-sound-effects"
echo "   https://freesound.org/search/?q=explosion+8bit"
echo ""
echo "3. powerup.wav - Power-up collection"
echo "   https://opengameart.org/content/power-up-sound-effect"
echo "   https://freesound.org/search/?q=powerup+game"
echo ""
echo "4. hit.wav - Damage/hit sound"
echo "   https://opengameart.org/content/hit-sounds"
echo "   https://freesound.org/search/?q=hit+impact"
echo ""
echo "5. game_over.wav - Game over jingle"
echo "   https://opengameart.org/content/game-over-sounds"
echo "   https://freesound.org/search/?q=game+over"
echo ""
echo "6. button_click.wav - UI click"
echo "   https://opengameart.org/content/ui-sound-effects"
echo "   https://freesound.org/search/?q=button+click+ui"
echo ""
echo "7. level_up.wav - Level up fanfare"
echo "   https://opengameart.org/content/level-up-sound-effect"
echo "   https://freesound.org/search/?q=level+up"
echo ""
echo "8. shop_purchase.wav - Purchase sound"
echo "   https://opengameart.org/content/cash-register-sound"
echo "   https://freesound.org/search/?q=coin+purchase"
echo ""
echo "--- MUSIC (save as .ogg in assets/music/) ---"
echo ""
echo "1. menu_theme.ogg - Space ambient menu music"
echo "   https://opengameart.org/content/space-ambient"
echo "   https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100407 (Cylinder Six)"
echo ""
echo "2. game_theme.ogg - Action/intense gameplay music"
echo "   https://opengameart.org/content/space-shooter-music"
echo "   https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100417 (Hitman)"
echo ""
echo "3. game_over_theme.ogg - Sad/melancholic short piece"
echo "   https://opengameart.org/content/game-over-music"
echo ""
echo "=== RECOMMENDED FREE RESOURCES ==="
echo ""
echo "OpenGameArt.org - https://opengameart.org/"
echo "  - Best for: 8-bit/retro sounds, game music"
echo "  - License: Most are CC0 (public domain)"
echo ""
echo "Freesound.org - https://freesound.org/"
echo "  - Best for: High-quality sound effects"
echo "  - License: CC0, CC-BY (check each sound)"
echo ""
echo "Incompetech (Kevin MacLeod) - https://incompetech.com/"
echo "  - Best for: Professional music tracks"
echo "  - License: CC-BY 3.0 (attribution required)"
echo ""
echo "Kenney.nl - https://kenney.nl/assets"
echo "  - Best for: Complete game audio packs"
echo "  - License: CC0 (public domain)"
echo ""
echo "=== AUDIO FORMAT TIPS ==="
echo ""
echo "Sound Effects:"
echo "  - Format: WAV (uncompressed) or OGG"
echo "  - Sample Rate: 44100 Hz"
echo "  - Channels: Mono (saves space, works for spatial audio)"
echo "  - Keep files small (<100KB each)"
echo ""
echo "Music:"
echo "  - Format: OGG Vorbis (compressed, good quality)"
echo "  - Sample Rate: 44100 Hz"
echo "  - Bitrate: 128-192 kbps"
echo "  - Channels: Stereo"
echo "  - Ensure seamless looping for menu/game themes"
echo ""


